[supervisord]
nodaemon=true

[program:slapd]
command=/usr/sbin/slapd -u ldap -g ldap -h "ldap:/// ldapi:///" -d 0
autostart=true
autorestart=true
priority=1

[program:postgres]
command=/usr/bin/postgres -D /var/lib/pgsql/data
autostart=true
autorestart=true
priority=1

[program:postgres]
command=/opt/jboss/wildfly/bin/